In [1]:
!pip install snorkel

Defaulting to user installation because normal site-packages is not writeable
Collecting snorkel
  Downloading snorkel-0.9.9-py3-none-any.whl (103 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 103.3/103.3 kB 3.4 MB/s eta 0:00:00
Collecting networkx>=2.2
  Downloading networkx-3.0-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 9.2 MB/s eta 0:00:00:00:0100:01
Collecting tqdm>=4.33.0
  Using cached tqdm-4.65.0-py3-none-any.whl (77 kB)
Collecting tensorboard>=2.9.1
  Downloading tensorboard-2.12.0-py3-none-any.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 2.4 MB/s eta 0:00:0000:0100:01m
Collecting munkres>=1.0.6
  Downloading munkres-1.1.4-py2.py3-none-any.whl (7.0 kB)
Requirement already satisfied: scikit-learn>=0.20.2 in /home/ggonzalv/.local/lib/python3.10/site-packages (from snorkel) (1.2.2)
Collecting torch>=1.2.0
  Downloading torch-1.13.1-cp310-cp310-manylinux1_x86_64.whl (887.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.5/887.5 MB 640.5 kB/s eta 0:00:0000:0100:12
Requirement already satisfied: numpy>=1.16.5 in /usr/lib/python3/dist-packages (from snorkel) (1.21.5)
Requirement already satisfied: scipy>=1.2.0 in /usr/lib/python3/dist-packages (from snorkel) (1.8.0)
Collecting pandas>=1.0.0
  Downloading pandas-1.5.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 2.5 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/lib/python3/dist-packages (from pandas>=1.0.0->snorkel) (2.8.1)
Requirement already satisfied: pytz>=2020.1 in /usr/lib/python3/dist-packages (from pandas>=1.0.0->snorkel) (2022.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/ggonzalv/.local/lib/python3.10/site-packages (from scikit-learn>=0.20.2->snorkel) (3.1.0)
Requirement already satisfied: joblib>=1.1.1 in /home/ggonzalv/.local/lib/python3.10/site-packages (from scikit-learn>=0.20.2->snorkel) (1.2.0)
Collecting absl-py>=0.4
  Downloading absl_py-1.4.0-py3-none-any.whl (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.5/126.5 kB 3.7 MB/s eta 0:00:00a 0:00:01
Collecting google-auth<3,>=1.6.3
  Downloading google_auth-2.16.2-py2.py3-none-any.whl (177 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.2/177.2 kB 7.6 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=41.0.0 in /usr/lib/python3/dist-packages (from tensorboard>=2.9.1->snorkel) (59.6.0)
Collecting requests<3,>=2.21.0
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting werkzeug>=1.0.1
  Using cached Werkzeug-2.2.3-py3-none-any.whl (233 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Downloading tensorboard_plugin_wit-1.8.1-py3-none-any.whl (781 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 781.3/781.3 kB 9.1 MB/s eta 0:00:00a 0:00:01
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Downloading google_auth_oauthlib-0.4.6-py2.py3-none-any.whl (18 kB)
Collecting markdown>=2.6.8
  Downloading Markdown-3.4.1-py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.3/93.3 kB 8.2 MB/s eta 0:00:00
Collecting grpcio>=1.48.2
  Downloading grpcio-1.51.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 2.6 MB/s eta 0:00:0000:0100:01m
Collecting tensorboard-data-server<0.8.0,>=0.7.0
  Downloading tensorboard_data_server-0.7.0-py3-none-manylinux2014_x86_64.whl (6.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 2.1 MB/s eta 0:00:0000:0100:01
Collecting protobuf>=3.19.6
  Downloading protobuf-4.22.1-cp37-abi3-manylinux2014_x86_64.whl (302 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.4/302.4 kB 6.2 MB/s eta 0:00:00a 0:00:01
Requirement already satisfied: wheel>=0.26 in /usr/lib/python3/dist-packages (from tensorboard>=2.9.1->snorkel) (0.37.1)
Collecting typing-extensions
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting nvidia-cuda-nvrtc-cu11==11.7.99
  Downloading nvidia_cuda_nvrtc_cu11-11.7.99-2-py3-none-manylinux1_x86_64.whl (21.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 2.0 MB/s eta 0:00:0000:0100:01
Collecting nvidia-cudnn-cu11==8.5.0.96
  Downloading nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (557.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 973.2 kB/s eta 0:00:0000:0100:08
Collecting nvidia-cublas-cu11==11.10.3.66
  Downloading nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 1.5 MB/s eta 0:00:0000:0100:05
Collecting nvidia-cuda-runtime-cu11==11.7.99
  Downloading nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 kB 4.5 MB/s eta 0:00:00a 0:00:01
Collecting pyasn1-modules>=0.2.1
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 6.9 MB/s eta 0:00:00
Collecting rsa<5,>=3.1.4
  Downloading rsa-4.9-py3-none-any.whl (34 kB)
Collecting cachetools<6.0,>=2.0.0
  Downloading cachetools-5.3.0-py3-none-any.whl (9.3 kB)
Requirement already satisfied: six>=1.9.0 in /usr/lib/python3/dist-packages (from google-auth<3,>=1.6.3->tensorboard>=2.9.1->snorkel) (1.16.0)
Collecting requests-oauthlib>=0.7.0
  Downloading requests_oauthlib-1.3.1-py2.py3-none-any.whl (23 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.14-py2.py3-none-any.whl (140 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.1.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.3/199.3 kB 8.8 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting MarkupSafe>=2.1.1
  Downloading MarkupSafe-2.1.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.1/77.1 kB 8.6 MB/s eta 0:00:00
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.9.1->snorkel) (3.2.0)
Installing collected packages: tensorboard-plugin-wit, pyasn1, munkres, urllib3, typing-extensions, tqdm, tensorboard-data-server, rsa, pyasn1-modules, protobuf, pandas, nvidia-cuda-runtime-cu11, nvidia-cuda-nvrtc-cu11, nvidia-cublas-cu11, networkx, MarkupSafe, markdown, idna, grpcio, charset-normalizer, certifi, cachetools, absl-py, werkzeug, requests, nvidia-cudnn-cu11, google-auth, torch, requests-oauthlib, google-auth-oauthlib, tensorboard, snorkel
  WARNING: The script tqdm is installed in '/home/ggonzalv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pyrsa-decrypt, pyrsa-encrypt, pyrsa-keygen, pyrsa-priv2pub, pyrsa-sign and pyrsa-verify are installed in '/home/ggonzalv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

  WARNING: The script markdown_py is installed in '/home/ggonzalv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer is installed in '/home/ggonzalv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts convert-caffe2-to-onnx, convert-onnx-to-caffe2 and torchrun are installed in '/home/ggonzalv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script google-oauthlib-tool is installed in '/home/ggonzalv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tensorboard is installed in '/home/ggonzalv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed MarkupSafe-2.1.2 absl-py-1.4.0 cachetools-5.3.0 certifi-2022.12.7 charset-normalizer-3.1.0 google-auth-2.16.2 google-auth-oauthlib-0.4.6 grpcio-1.51.3 idna-3.4 markdown-3.4.1 munkres-1.1.4 networkx-3.0 nvidia-cublas-cu11-11.10.3.66 nvidia-cuda-nvrtc-cu11-11.7.99 nvidia-cuda-runtime-cu11-11.7.99 nvidia-cudnn-cu11-8.5.0.96 pandas-1.5.3 protobuf-4.22.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 requests-2.28.2 requests-oauthlib-1.3.1 rsa-4.9 snorkel-0.9.9 tensorboard-2.12.0 tensorboard-data-server-0.7.0 tensorboard-plugin-wit-1.8.1 torch-1.13.1 tqdm-4.65.0 typing-extensions-4.5.0 urllib3-1.26.14 werkzeug-2.2.3

In [5]:
# Import necessary packages
import pandas as pd
from snorkel.labeling import labeling_function, PandasLFApplier, LFAnalysis
from snorkel.analysis import get_label_buckets
from snorkel.labeling.model import MajorityLabelVoter, LabelModel

In [6]:
# Read the data
train_df = pd.read_pickle("https://github.com/khuyentran1401/Data-science/blob/master/feature_engineering/snorkel_example/train_fake_jobs.pkl?raw=true")
test_df = pd.read_pickle("https://github.com/khuyentran1401/Data-science/blob/master/feature_engineering/snorkel_example/test_fake_jobs.pkl?raw=true")

train_df

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
12276,12277,Big Data Analyst,"GB, WSM, London",Product Ops,NaN,Founded in 2010 by a team from Google’s London...,Qubit: Cutting Edge Big Data EngineeringQubit ...,"What you'll need: A background in consulting, ...",Plenty of perks:As well as the opportunity to ...,0,1,1,Full-time,Associate,Bachelor's Degree,Internet,Product Management,0
14680,14681,Instructional Advocate,"US, GA, Savannah",NaN,NaN,We are an after-school program committed to as...,21st Century Community Learning Centers is an ...,Bachelor's Degree or an Associate's Degree; or...,NaN,0,1,0,Part-time,NaN,NaN,NaN,Education,0
16518,16519,Software Developer,"US, FL, Gainesville",NaN,NaN,352 Inc. is a full-service digital agency crea...,We partner with great clients to build smart s...,3-5 years of great c# work Experience in mvc o...,What You’ll GetFreedom: We trust you to do you...,0,1,0,Full-time,Mid-Senior level,NaN,Computer Software,Information Technology,0
15478,15479,Internship in India,"IN, , Bangalore",NaN,NaN,,"London is a fast paced city of culture, divers...",,As specialists in delivering high quality and ...,0,1,0,NaN,NaN,NaN,NaN,NaN,0
16348,16349,Web Developer Backend Microservices (m/f),"DE, BE, 10969",Engineering,NaN,airfy prägt sicheres und einfach zu bedienende...,Design and develop a microservice platform for...,"Senior level experience with web backends, esp...",Flat hierarchies and a productive work environ...,0,1,0,Full-time,Associate,Bachelor's Degree,Internet,Engineering,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9225,9226,Senior Tax Professional for Product Manager,"US, CA, San Francisco",Product,100000-150000,Balanced Labs exists to provide accountants an...,Never before has a job in tax looked more inte...,10+ years tax experience. Extensive knowledge ...,NaN,0,1,1,Full-time,Director,Bachelor's Degree,Accounting,Strategy/Planning,0
13123,13124,QA Engineer,"US, CA, San Mateo",NaN,NaN,Tile is one of the most successful crowd-funde...,"The RoleHere at Tile, we are looking for a sma...","Mandatory Qualities Tech enthusiast, you love ...",Own equity in the company. Every employee is a...,0,1,0,Full-time,Associate,Bachelor's Degree,Consumer Electronics,Engineering,0
9845,9846,Senior QA Engineer,"IN, , Hyderabad",Information Technology,NaN,#url_ddb080358fa5eecf5a67c649cfb4ffc343c484389...,Responsibilities:* Acquire and maintain a comp...,Required Skills and Experience: Minimum of fiv...,What Is OfferedOur client's core values drive ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Marketing and Advertising,Engineering,1
10799,10800,Customer Service Associate,"US, CT, Hartford",NaN,NaN,"Novitex Enterprise Solutions, formerly Pitney ...",We are currently seeking a Customer Service As...,Minimum Requirements: Minimum of 2 years custo...,NaN,0,1,0,Full-time,Entry level,High School or equivalent,Facilities Services,Customer Service,0
2732,2733,Peoplesoft HCM Lead - Programmer/Analyst,"US, PA, Philadelphia",NaN,NaN,,POSITION OVERVIEW:This position is responsible...,minimum qualifications: Bachelor's degree ( in...,My client company is a well established organi...,0,0,1,NaN,NaN,NaN,NaN,NaN,0

In [7]:
# Give a meaningful name to each value
FAKE = 1
REAL = 0
ABSTAIN = -1

# Create labeling functions

@labeling_function()
def no_company_profile(x: pd.Series):
    return FAKE if x.company_profile == "" else ABSTAIN


@labeling_function()
def no_company_logo(x: pd.Series):
    return FAKE if x.has_company_logo == 0 else ABSTAIN


@labeling_function()
def has_background_check(x: pd.Series):
    return REAL if "background check" in x.requirements else ABSTAIN


@labeling_function()
def required_experience(x: pd.Series):
    return REAL if x.required_experience else ABSTAIN


@labeling_function()
def required_education(x: pd.Series):
    return REAL if x.required_education else ABSTAIN

In [8]:
# Create the pandas applier object and apply the labeling functions to the dataframe

lfs = [
    no_company_profile,
    no_company_logo,
    has_background_check,
    required_experience,
    required_education,
]

applier = PandasLFApplier(lfs=lfs)
L_train = applier.apply(df=train_df)

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13410/13410 [00:00<00:00, 34949.82it/s]

In [9]:
# Look at the data
L_train

array([[-1, -1, -1,  0,  0],
       [-1, -1, -1,  0,  0],
       [-1, -1, -1,  0,  0],
       ...,
       [-1, -1, -1,  0,  0],
       [-1, -1,  0,  0,  0],
       [ 1,  1, -1,  0,  0]])

In [10]:
# Evaluate labeling functions using real labels
LFAnalysis(L=L_train, lfs=lfs).lf_summary(Y=train_df.fraudulent.values)

,j,Polarity,Coverage,Overlaps,Conflicts,Correct,Incorrect,Emp. Acc.
no_company_profile,0,[1],0.186204,0.186204,0.186204,459,2038,0.183821
no_company_logo,1,[1],0.205742,0.205742,0.205742,459,2300,0.166365
has_background_check,2,[0],0.035496,0.035496,0.002759,464,12,0.974790
required_experience,3,[0],1.000000,1.000000,0.244295,12741,669,0.950112
required_education,4,[0],1.000000,1.000000,0.244295,12741,669,0.950112

In [11]:
# Evaluate labeling functions in case there were no labels
LFAnalysis(L=L_train, lfs=lfs).lf_summary()

                      j Polarity  Coverage  Overlaps  Conflicts
no_company_profile    0      [1]  0.186204  0.186204   0.186204
no_company_logo       1      [1]  0.205742  0.205742   0.205742
has_background_check  2      [0]  0.035496  0.035496   0.002759
required_experience   3      [0]  1.000000  1.000000   0.244295
required_education    4      [0]  1.000000  1.000000   0.244295

In [12]:
# Evauate conflicts between the different labeling functions
buckets = get_label_buckets(L_train[:, 1], L_train[:, 3])

train_df.iloc[buckets[(FAKE, REAL)]].sample(10, random_state=1)[
    ["has_company_logo", "required_experience", "fraudulent"]
]

       has_company_logo required_experience  fraudulent
16586                 0                 NaN           0
16246                 0                 NaN           0
4695                  0                 NaN           1
1292                  0           Associate           0
16188                 0                 NaN           0
1784                  0         Entry level           0
17517                 0                 NaN           1
6049                  0                 NaN           0
5611                  0      Not Applicable           0
1876                  0                 NaN           0

In [13]:
# Combine the predictions to have your final classification
# MajorityLabelVoter decides the final prediction based on a majority vote between labeling functions

# Create the model
majority_model = MajorityLabelVoter()
preds_train = majority_model.predict(L=L_train)

# Get test predictions
L_test = applier.apply(df=test_df)

# Get train and test labels
Y_train = train_df["fraudulent"]
Y_test = test_df["fraudulent"]

# Evaluate
majority_acc = majority_model.score(L=L_test, Y=Y_test)[
    "accuracy"
]
print(f"{'Majority Vote Accuracy:':<25} {majority_acc * 100:.1f}%")

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4470/4470 [00:00<00:00, 33334.47it/s]
WARNING:root:Metrics calculated over data points with non-abstain labels only

Majority Vote Accuracy:   98.0%

In [14]:
#LabelModel is an alternative which produces noise-aware training labels
label_model = LabelModel(cardinality=2, verbose=True)
label_model.fit(L_train=L_train, n_epochs=500, log_freq=100, seed=1)

# Evaluate the model
label_model_acc = label_model.score(L=L_test, Y=Y_test)["accuracy"]
print(f"{'Label Model Accuracy:':<25} {label_model_acc * 100:.1f}%")

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 500/500 [00:00<00:00, 3411.43epoch/s]
WARNING:root:Metrics calculated over data points with non-abstain labels only

Label Model Accuracy:     77.4%

## References

https://towardsdatascience.com/snorkel-programmatically-build-training-data-in-python-712fc39649fe

https://www.youtube.com/watch?v=Prr53wXiHfM&feature=youtu.be